[build]
command = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "expense_tracker.settings.production"
PYTHONPATH = "." 