[build]
command = "chmod +x scripts/build.sh && ./scripts/build.sh"

[deploy]
startCommand = "chmod +x scripts/start.sh && ./scripts/start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "expense_tracker.settings.production"
PYTHONPATH = "."
# Multi-user deployment settings
ENABLE_MULTI_USER = "true"
DEFAULT_USER_LIMIT = "1000" 