# Generated by Django 5.2.2 on 2025-06-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='User Message')),
                ('ai_response', models.TextField(verbose_name='AI Response')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed')),
                ('has_voice_input', models.BooleanField(default=False, verbose_name='Has Voice Input')),
                ('voice_transcript', models.TextField(blank=True, verbose_name='Voice Transcript')),
                ('parsed_date', models.DateField(blank=True, null=True, verbose_name='Parsed Date')),
                ('language', models.CharField(choices=[('vi', 'Vietnamese'), ('en', 'English')], default='vi', max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('suggested_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction', verbose_name='Suggested Transaction')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
