# Generated by Django 5.2.2 on 2025-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', '🔴 Chi tiêu'), ('saving', '🟢 Tiết kiệm'), ('investment', '🔵 Đầu tư')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Amount')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('expense_category', models.CharField(blank=True, choices=[('food', '🍜 Ăn uống'), ('coffee', '☕ Coffee'), ('transport', '🚗 Di chuyển'), ('shopping', '🛒 Mua sắm'), ('entertainment', '🎬 Giải trí'), ('health', '🏥 Sức khỏe'), ('education', '📚 Giáo dục'), ('utilities', '⚡ Tiện ích'), ('other', '📦 Khác')], max_length=20, null=True, verbose_name='Expense Category')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='AI Confidence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('total_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Expense')),
                ('total_saving', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Saving')),
                ('total_investment', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total Investment')),
                ('net_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Net Total')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Monthly Total',
                'verbose_name_plural': 'Monthly Totals',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
