# Generated by Django 5.2.2 on 2025-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_bank_integration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankconfig',
            name='custom_bank_name',
            field=models.CharField(blank=True, help_text='Custom bank display name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbankconfig',
            name='is_custom_bank',
            field=models.BooleanField(default=False, help_text='Whether this is a user-defined custom bank'),
        ),
        migrations.AlterField(
            model_name='userbankconfig',
            name='bank_code',
            field=models.CharField(max_length=50),
        ),
    ]
